[project]
name = "frida-freq"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.3",
    "python-dotenv>=1.0.0",
    "certifi>=2023.0.0",
]
